[package]
name = "rust_test_sample"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
panic-halt = "0.2.0"

[unstable]
build-std = ["core"]

[profile.release]
panic = "abort"
